name: Parallel Test Build
on: push
jobs:
  addToCart-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:addToCart

      - name: Cypress Test Report
        uses: actions/upload-artifact@v3
        with:
          name: Mochawesome HTML Report - Add To Cart
          path: cypress/reports/html

  registerTest-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:registerTest

      - name: Cypress Test Report
        uses: actions/upload-artifact@v3
        with:
          name: Mochawesome HTML Report - Reg Flow
          path: cypress/reports/html
